name: Push To Windows VM
#Name of the workflow

on: 
push:
branches: [main]
#Runs every time main is pushed to

jobs: 
deploy: 
runs-on: self-hosted
#Deploys on the self-hosted Uni VM

steps: 
- uses: actions/checkout@v4
- name: deploy to IIS folder
- Shell: powershell
#uses powershell on the local machine
run: |
$src = "${env:GITHUB_WORKSPACE}\*" #sets the source to be the current Github repository.
$dst = "C:\inetpub\wwwroot\"   #sets the destination to be the website folder. 

New-item -ItemType Directory -Force -Path $dst | Out-Null #Ensures the iis folder exists. 
Copy-Item -Path $src -Destination $dst -Recurse -Force #Copies repository across the IIS folder.
